default:
	gcc p1socket.c -o p1socket
	gcc p2socket.c -o p2socket
fifo:
	gcc p1fifo.c -o p1fifo
	gcc p2fifo.c -o p2fifo
msg:
	gcc p1msg.c -o p1msg
	gcc p2msg.c -o p2msg
clean:
	rm -f p1fifo p2fifo p1msg p2msg p1socket p2socket socket